"""
blockchain.py — Polygon Amoy Testnet Integration via Web3.py

Provides a `BlockchainClient` class that connects to the Polygon Amoy Testnet
through an Alchemy RPC endpoint, and writes/reads FaceRecord entries to/from
a deployed Solidity smart contract.
"""

import json
from web3 import Web3
from web3.exceptions import ContractLogicError


class BlockchainConnectionError(Exception):
    """Raised when the Web3 provider cannot connect or chain ID is wrong."""
    pass


class TransactionFailedError(Exception):
    """Raised when a blockchain transaction fails to send or confirm."""
    pass


# ABI for the deployed FaceRecord contract (auto-generated by solc)
FACE_RECORD_ABI = json.loads("""
[
    {
        "anonymous": false,
        "inputs": [
            {"indexed": true, "internalType": "uint256", "name": "recordId", "type": "uint256"},
            {"indexed": false, "internalType": "string", "name": "faceHash", "type": "string"},
            {"indexed": false, "internalType": "string", "name": "matchedUrl", "type": "string"},
            {"indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256"},
            {"indexed": true, "internalType": "address", "name": "submitter", "type": "address"}
        ],
        "name": "RecordStored",
        "type": "event"
    },
    {
        "inputs": [
            {"internalType": "string", "name": "_faceHash", "type": "string"},
            {"internalType": "string", "name": "_matchedUrl", "type": "string"}
        ],
        "name": "storeRecord",
        "outputs": [
            {"internalType": "uint256", "name": "recordId", "type": "uint256"}
        ],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "_recordId", "type": "uint256"}
        ],
        "name": "getRecord",
        "outputs": [
            {"internalType": "string", "name": "faceHash", "type": "string"},
            {"internalType": "string", "name": "matchedUrl", "type": "string"},
            {"internalType": "uint256", "name": "timestamp", "type": "uint256"},
            {"internalType": "address", "name": "submitter", "type": "address"}
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [],
        "name": "recordCount",
        "outputs": [
            {"internalType": "uint256", "name": "", "type": "uint256"}
        ],
        "stateMutability": "view",
        "type": "function"
    }
]
""")

# Polygon Amoy Testnet chain ID
AMOY_CHAIN_ID = 80002
EXPLORER_BASE = "https://amoy.polygonscan.com"


class BlockchainClient:
    """
    High-level client for interacting with the FaceRecord smart contract
    on the Polygon Amoy Testnet.

    Usage
    -----
    >>> client = BlockchainClient(rpc_url, private_key, contract_address)
    >>> client.connect()
    >>> result = client.store_record(face_hash, matched_url)
    >>> print(result["explorer_url"])
    """

    def __init__(self, rpc_url: str, private_key: str, contract_address: str):
        """
        Parameters
        ----------
        rpc_url : str
            Alchemy (or other) RPC URL for Polygon Amoy.
        private_key : str
            Hex-encoded private key of the submitter wallet (with 0x prefix or without).
        contract_address : str
            Address of the deployed FaceRecord contract (checksummed).
        """
        if not rpc_url or not rpc_url.strip():
            raise BlockchainConnectionError("ALCHEMY_RPC_URL is missing or empty.")
        if not private_key or not private_key.strip():
            raise BlockchainConnectionError("PRIVATE_KEY is missing or empty.")
        if not contract_address or not contract_address.strip():
            raise BlockchainConnectionError(
                "CONTRACT_ADDRESS is missing or empty. Deploy the contract first."
            )

        self.rpc_url = rpc_url.strip()
        self.private_key = private_key.strip()
        if not self.private_key.startswith("0x"):
            self.private_key = "0x" + self.private_key

        self.contract_address = contract_address.strip()
        self.w3 = None
        self.contract = None
        self.account = None

    def connect(self) -> bool:
        """
        Establish a connection to the Polygon Amoy Testnet and validate
        the chain ID and contract address.

        Returns
        -------
        bool
            True if connection is successful.

        Raises
        ------
        BlockchainConnectionError
            If the RPC is unreachable, chain ID is wrong, or the contract
            address is invalid.
        """
        try:
            self.w3 = Web3(Web3.HTTPProvider(self.rpc_url))
        except Exception as exc:
            raise BlockchainConnectionError(
                f"Failed to create Web3 provider: {exc}"
            ) from exc

        if not self.w3.is_connected():
            raise BlockchainConnectionError(
                f"Cannot connect to RPC endpoint: {self.rpc_url}\n"
                "Check your ALCHEMY_RPC_URL in .env and your internet connection."
            )

        # Validate chain ID
        chain_id = self.w3.eth.chain_id
        if chain_id != AMOY_CHAIN_ID:
            raise BlockchainConnectionError(
                f"Expected Polygon Amoy chain ID {AMOY_CHAIN_ID}, "
                f"but connected to chain {chain_id}. "
                "Check your ALCHEMY_RPC_URL."
            )

        # Derive account from private key
        try:
            self.account = self.w3.eth.account.from_key(self.private_key)
        except Exception as exc:
            raise BlockchainConnectionError(
                f"Invalid PRIVATE_KEY: {exc}"
            ) from exc

        # Validate contract address and create contract instance
        try:
            checksum_addr = self.w3.to_checksum_address(self.contract_address)
        except Exception as exc:
            raise BlockchainConnectionError(
                f"Invalid CONTRACT_ADDRESS: {exc}"
            ) from exc

        self.contract = self.w3.eth.contract(
            address=checksum_addr,
            abi=FACE_RECORD_ABI,
        )

        return True

    def store_record(self, face_hash: str, matched_url: str) -> dict:
        """
        Write a face-verification record to the blockchain.

        Parameters
        ----------
        face_hash : str
            SHA-256 hex digest of the face encoding.
        matched_url : str
            Public URL matched via reverse image search.

        Returns
        -------
        dict
            {
                "tx_hash":      str,   # Transaction hash (0x-prefixed)
                "block_number": int,   # Block in which the tx was mined
                "gas_used":     int,   # Gas consumed
                "explorer_url": str,   # Direct Polygonscan link
                "record_id":    int,   # On-chain record ID
                "wallet":       str,   # Submitter wallet address
            }

        Raises
        ------
        TransactionFailedError
            If the transaction cannot be built, signed, sent, or confirmed.
        """
        if self.contract is None:
            raise TransactionFailedError("Not connected. Call connect() first.")

        try:
            # Get the current nonce for the submitter account
            nonce = self.w3.eth.get_transaction_count(self.account.address)

            # Build the transaction
            tx = self.contract.functions.storeRecord(
                face_hash, matched_url
            ).build_transaction({
                "chainId": AMOY_CHAIN_ID,
                "from": self.account.address,
                "nonce": nonce,
                "gas": 500_000,  # generous limit; actual usage is ~200k
                "maxFeePerGas": self.w3.to_wei("50", "gwei"),
                "maxPriorityFeePerGas": self.w3.to_wei("30", "gwei"),
            })

            # Sign and send
            signed_tx = self.w3.eth.account.sign_transaction(tx, self.private_key)
            tx_hash = self.w3.eth.send_raw_transaction(signed_tx.raw_transaction)

            # Wait for confirmation
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)

        except TransactionFailedError:
            raise
        except ContractLogicError as exc:
            raise TransactionFailedError(
                f"Smart contract reverted: {exc}"
            ) from exc
        except Exception as exc:
            raise TransactionFailedError(
                f"Blockchain transaction failed: {exc}"
            ) from exc

        if receipt.status != 1:
            raise TransactionFailedError(
                f"Transaction reverted on-chain. Hash: {tx_hash.hex()}"
            )

        # Parse the RecordStored event to get the record ID
        record_id = None
        try:
            logs = self.contract.events.RecordStored().process_receipt(receipt)
            if logs:
                record_id = logs[0]["args"]["recordId"]
        except Exception:
            record_id = None  # Non-critical; the tx hash is sufficient proof

        tx_hash_hex = tx_hash.hex()
        if not tx_hash_hex.startswith("0x"):
            tx_hash_hex = "0x" + tx_hash_hex

        return {
            "tx_hash": tx_hash_hex,
            "block_number": receipt.blockNumber,
            "gas_used": receipt.gasUsed,
            "explorer_url": f"{EXPLORER_BASE}/tx/{tx_hash_hex}",
            "record_id": record_id,
            "wallet": self.account.address,
        }

    def get_record(self, record_id: int) -> dict:
        """
        Read a record from the blockchain by its ID.

        Parameters
        ----------
        record_id : int
            The on-chain record ID.

        Returns
        -------
        dict
            {"face_hash": str, "matched_url": str, "timestamp": int, "submitter": str}

        Raises
        ------
        TransactionFailedError
            If the read call fails.
        """
        if self.contract is None:
            raise TransactionFailedError("Not connected. Call connect() first.")

        try:
            result = self.contract.functions.getRecord(record_id).call()
            return {
                "face_hash": result[0],
                "matched_url": result[1],
                "timestamp": result[2],
                "submitter": result[3],
            }
        except ContractLogicError as exc:
            raise TransactionFailedError(
                f"Contract call failed (record may not exist): {exc}"
            ) from exc
        except Exception as exc:
            raise TransactionFailedError(
                f"Failed to read record: {exc}"
            ) from exc
